### PR TITLE
SimpleCov added to gemfile

### PR DESCRIPTION
**Pull request by FayeCarter**

### CODE REVIEW

**Review by Edward-Phillips — APPROVED** [review]
LGTM

**Review by hturnbull93 — APPROVED** [review]
LGTM :+1:

**Review by hturnbull93 — CHANGES_REQUESTED** [review]
I have tried this but simplecov doesn't appear when running rspec? not sure.
Can we get it in the console?

**Comment by tommyrharper** [comment]
It should be showing the coverage when running spec, but it is quite subtle in white text at the end.

**Comment by FayeCarter** [comment]
Spec_helper has been updated with simplecov console

**Review by Edward-Phillips — APPROVED** [review]
LGTM

**Comment by Edward-Phillips** [comment]
Legtm (Looks even good-er to me)

**Pull request merged**
